### ISSUE TITLE
Error handling when the uid, gid doens't exist.

### ISSUE THREAD

**Issue by negletios** [jandre/node-userid#3]
I need some kind of error handling in case the users / groups doesn't exist.

Right it throws : Segmentation fault.

It would be a nice to have :+1:

**Comment by jandre** [comment]
doh I thought I fixed this! I'll check it out.

**Comment by jandre** [comment]
can you give me some test code to reproduce, and also tell me which platform you are seeing the error on?

Thanks!
Jen

**Comment by negletios** [comment]
I am using it on Debian Jessie / 8. 

The code is the same as your doc example. FYI I am using it inside a grunt task file. I don't know if that has anything to do :) 

 Just test it with a username / group that doesn't exist.

**Comment by streamich** [comment]
Crashes with "Segmentation fault" on Ubuntu 14.04 when running example in README, because group "wheel" does not exist.

**Comment by jandre** [comment]
thanks all.  What version of node so I can be sure to replicate?

**Comment by jandre** [comment]
0.1.3 should fix this; pushed to repo.  Thanks!

**Comment by negletios** [comment]
:+1:
